# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jcloud
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.threads.virtual.enabled=true

storage.location=./data/storage

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
